const text = [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id molestie ex. Duis laoreet ipsum nibh, non facilisis ante auctor non. Phasellus cursus ex a est lacinia, quis hendrerit metus dignissim. Ut scelerisque lectus at metus sollicitudin, commodo condimentum nulla pretium. Donec bibendum, neque vitae faucibus viverra, nisi eros dapibus massa, dictum bibendum felis nisl a felis. Donec vitae dignissim ligula. Etiam congue ullamcorper purus, congue molestie sapien iaculis vel. Sed quis ipsum sed ante gravida tincidunt. Donec cursus elementum diam, imperdiet tristique magna sagittis non. Vivamus scelerisque eu ex et venenatis. Curabitur fringilla dolor a nisl fermentum, a pharetra enim aliquet. Etiam bibendum tempus elit, non iaculis magna tempus nec. Pellentesque mauris quam, pharetra ac libero nec, gravida sodales lacus. Vestibulum accumsan nisi non condimentum porta. Phasellus et arcu eleifend risus dapibus commodo vel quis risus.`,
    `Morbi vulputate pharetra velit. Praesent interdum mi vitae velit consequat tempor. In aliquam libero id semper facilisis. Phasellus ut sem urna. Maecenas pulvinar quam cursus commodo euismod. Vestibulum velit nunc, dapibus sit amet ipsum eget, ullamcorper suscipit erat. Maecenas in tellus convallis, pharetra purus sed, malesuada quam. Sed ut dui et diam porta finibus. In viverra semper ligula vitae ornare. Sed malesuada purus vitae massa rhoncus consectetur. Vestibulum ligula orci, tristique id ante eget, viverra facilisis lacus. Maecenas molestie placerat lorem sit amet porta. Morbi commodo dignissim justo, vel vehicula est mollis id. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque molestie egestas lacus at volutpat.`,
    `Pellentesque id aliquet augue. Praesent elementum, elit a rhoncus condimentum, diam nibh pretium dolor, sed vulputate est erat varius augue. Nunc eget mi nec justo laoreet suscipit. Phasellus a dapibus elit. Integer non semper felis, eu pellentesque turpis. Sed tincidunt eget orci sed ultricies. Sed vel leo vitae ante sagittis elementum. Integer ut nisi at massa volutpat congue.`,
    `Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id ipsum porttitor, tincidunt purus id, gravida ante. Fusce in nulla sit amet ex auctor volutpat. Donec convallis pretium quam. Etiam a facilisis dui. Quisque feugiat tellus vel massa pharetra, vitae tristique arcu finibus. Sed ac iaculis urna, fermentum tristique velit. Nullam blandit commodo nisi sodales porta. Donec tincidunt non lorem vitae sollicitudin. Aenean nec justo arcu. Duis posuere lacus sit amet leo blandit, a molestie odio imperdiet. Sed pulvinar fermentum ligula at sodales.`,
    `In sed erat viverra, aliquet tellus nec, bibendum nunc. Donec mattis mi ut quam mattis, at convallis dolor dictum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum accumsan metus velit, sed tincidunt sapien commodo non. Sed sit amet laoreet purus. Nullam bibendum condimentum ipsum, ut euismod erat volutpat sit amet. Maecenas eu viverra felis. Vivamus congue rhoncus magna eget eleifend. Donec vel accumsan velit. In in enim eu lorem hendrerit pulvinar. Aliquam et est vitae velit dictum accumsan.`,
    `Integer condimentum sem id libero finibus eleifend. Integer mollis pulvinar leo, id pulvinar nulla rhoncus eget. Quisque condimentum diam ac ex tempor, eu molestie purus vestibulum. Ut sit amet diam sit amet sem lobortis venenatis. Duis commodo placerat massa. Praesent gravida interdum ante vel finibus. Sed cursus facilisis dui et luctus. Maecenas tincidunt mauris ut maximus imperdiet. Integer rhoncus feugiat erat at semper. Mauris ipsum lacus, finibus sit amet felis eget, tempor bibendum est. Proin pulvinar est augue, quis dignissim quam feugiat porttitor. Sed in elementum mi. Phasellus blandit suscipit convallis. Etiam sit amet lobortis purus. Donec placerat eu erat sit amet pharetra. Nullam volutpat nisi dolor, nec vestibulum ligula efficitur id.`,
    `Aenean scelerisque blandit maximus. Integer fermentum eu turpis at facilisis. Fusce tempor dapibus sodales. Morbi elementum metus at lectus sagittis fringilla. In quis nisi mi. Aliquam ut rutrum massa. Vivamus dignissim fermentum diam, ut fringilla diam porta mattis. Cras ac nibh aliquam, pulvinar metus a, tempus tortor. Nunc vehicula ornare arcu sed rutrum. Nunc eu malesuada nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sit amet aliquam nibh, ac viverra leo. In efficitur, purus eget fringilla consectetur, risus orci condimentum odio, ut tempor nunc dui non urna. Donec vitae ultricies metus, eu viverra lacus. Curabitur elementum malesuada nisi. Maecenas nec ex dignissim, commodo tortor sit amet, eleifend nisl.`,
    `Morbi pulvinar, libero eget accumsan tristique, lacus nisi maximus risus, non blandit nisl ipsum nec orci. Nunc euismod mi quis urna ullamcorper tincidunt. Maecenas eu cursus enim. Phasellus sed quam et ante tincidunt faucibus non non lacus. Nunc dignissim varius mauris. Ut sit amet orci lectus. Ut pellentesque, lectus mattis porttitor malesuada, justo mauris ullamcorper mi, vel posuere risus ipsum sit amet sapien. Nam ornare lorem ac nisi molestie facilisis. Maecenas fringilla congue ultrices.`,
    `Maecenas aliquet sollicitudin libero molestie accumsan. Sed eu dui euismod felis blandit rutrum. Sed elementum tempor lacus, eu dignissim nunc auctor quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pretium ligula malesuada aliquam euismod. Sed convallis aliquet libero at maximus. Etiam vitae cursus velit, a consectetur dui. Integer vitae lacus mi.`,
    `Quisque viverra velit sed diam tempus pretium. Etiam consequat, justo at porttitor accumsan, turpis ex tincidunt magna, non pulvinar ante orci non ex. Etiam vel felis cursus, viverra eros sed, luctus felis. Aenean nunc urna, tincidunt at enim ac, ornare porta dolor. Aliquam pretium sem et ante imperdiet tincidunt. Maecenas lacinia, dolor at eleifend euismod, urna diam congue est, eu vestibulum justo est tempor ligula. Nam congue lobortis eros quis accumsan. Aenean vulputate velit eget nulla blandit pellentesque. Aenean imperdiet, eros eget lacinia sollicitudin, metus urna sollicitudin ex, sit amet maximus ipsum leo eu justo. Etiam hendrerit ligula nec metus molestie, ac commodo lacus tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.`
]

export default text